const dicionario = {
  // A
  "abacate": { classe: "substantivo", gravidade: null },
  "abafado": { classe: "adjetivo", gravidade: -1 },
  "abaixar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "abaixou", presente: "abaixa", futuro: "abaixará" } },
  "abalado": { classe: "adjetivo", gravidade: -1 },
  "abalar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "abalou", presente: "abala", futuro: "abalará" } },
  "abanar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "abanou", presente: "abana", futuro: "abanará" } },
  "abandonar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "abandonou", presente: "abandona", futuro: "abandonará" } },
  "abarcar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "abarcou", presente: "abarca", futuro: "abarcará" } },
  "abastecer": { classe: "verbo", gravidade: 1, conjugacao: { passado: "abasteceu", presente: "abastece", futuro: "abastecerá" } },
  "abatido": { classe: "adjetivo", gravidade: -1 },
  "abelha": { classe: "substantivo", gravidade: null },
  "aberração": { classe: "substantivo", gravidade: null },
  "abismo": { classe: "substantivo", gravidade: null },
  "abjeto": { classe: "adjetivo", gravidade: -2 },
  "abnegado": { classe: "adjetivo", gravidade: 2 },
  "abnegar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "abnegou", presente: "abnega", futuro: "abnegará" } },
  "abençoar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "abençoou", presente: "abençoa", futuro: "abençoará" } },
  "abóbora": { classe: "substantivo", gravidade: null },
  "abolar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "abolou", presente: "abola", futuro: "abolará" } },
  "abolir": { classe: "verbo", gravidade: 1, conjugacao: { passado: "aboliu", presente: "abole", futuro: "abolirá" } },
  "abominável": { classe: "adjetivo", gravidade: -2 },
  "aborrecer": { classe: "verbo", gravidade: -1, conjugacao: { passado: "aborreceu", presente: "aborrece", futuro: "aborrecerá" } },
  "abraço": { classe: "substantivo", gravidade: null },
  "abrasador": { classe: "adjetivo", gravidade: -1 },
  "abrigar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "abrigou", presente: "abriga", futuro: "abrigará" } },
  "brilhante": { classe: "adjetivo", gravidade: 2 },
  "abrupto": { classe: "adjetivo", gravidade: -1 },
  "absoluto": { classe: "adjetivo", gravidade: 0 },
  "absorver": { classe: "verbo", gravidade: 0, conjugacao: { passado: "absorveu", presente: "absorve", futuro: "absorverá" } },
  "abster": { classe: "verbo", gravidade: 0, conjugacao: { passado: "absteve", presente: "abstém", futuro: "absterá" } },
  "abstrato": { classe: "adjetivo", gravidade: 0 },
  "absurdo": { classe: "adjetivo", gravidade: -1 },
  "abundante": { classe: "adjetivo", gravidade: 1 },
  "abusar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "abusou", presente: "abusa", futuro: "abusará" } },
  "acabar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "acabou", presente: "acaba", futuro: "acabará" } },
  "acalmar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "acalmou", presente: "acalma", futuro: "acalmará" } },
  "acampar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "acampou", presente: "acampa", futuro: "acampará" } },
  "aceitar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "aceitou", presente: "aceita", futuro: "aceitará" } },
  "acelerar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "acelerou", presente: "acelera", futuro: "acelerará" } },
  "acenar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "acenou", presente: "acena", futuro: "acenará" } },
  "acervo": { classe: "substantivo", gravidade: null },
  "acerto": { classe: "substantivo", gravidade: null },
  "aceso": { classe: "adjetivo", gravidade: 0 },
  "achar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "achou", presente: "acha", futuro: "achará" } },
  "ácido": { classe: "adjetivo", gravidade: -1 },
  "acima": { classe: "advérbio", gravidade: null },
  "acobardado": { classe: "adjetivo", gravidade: -2 },
  "acolher": { classe: "verbo", gravidade: 2, conjugacao: { passado: "acolheu", presente: "acolhe", futuro: "acolherá" } },
  "acompanhar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "acompanhou", presente: "acompanha", futuro: "acompanhará" } },
  "aconchegante": { classe: "adjetivo", gravidade: 2 },
  "acontecer": { classe: "verbo", gravidade: 0, conjugacao: { passado: "aconteceu", presente: "acontece", futuro: "acontecerá" } },
  "acordar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "acordou", presente: "acorda", futuro: "acordará" } },
  "acorrentar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "acorrentou", presente: "acorrenta", futuro: "acorrentará" } },
  "acreditar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "acreditou", presente: "acredita", futuro: "acreditará" } },
  "acumular": { classe: "verbo", gravidade: 0, conjugacao: { passado: "acumulou", presente: "acumula", futuro: "acumulará" } },
  "acusar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "acusou", presente: "acusa", futuro: "acusará" } },
  "adaptar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "adaptou", presente: "adapta", futuro: "adaptará" } },
  "adensar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "adensou", presente: "adensa", futuro: "adensará" } },
  "adequado": { classe: "adjetivo", gravidade: 1 },
  "adiantar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "adiantou", presente: "adianta", futuro: "adiantará" } },
  "adiar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "adiou", presente: "adia", futuro: "adiará" } },
  "admirar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "admirou", presente: "admira", futuro: "admirará" } },
  "admitir": { classe: "verbo", gravidade: 0, conjugacao: { passado: "admitiu", presente: "admite", futuro: "admitirá" } },
  "adoecer": { classe: "verbo", gravidade: -2, conjugacao: { passado: "adoeceu", presente: "adoece", futuro: "adoecerá" } },
  "adorar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "adorou", presente: "adora", futuro: "adorará" } },
  "adormecer": { classe: "verbo", gravidade: 0, conjugacao: { passado: "adormeceu", presente: "adormece", futuro: "adormecerá" } },
  "adotar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "adotou", presente: "adota", futuro: "adotará" } },
  "adular": { classe: "verbo", gravidade: -1, conjugacao: { passado: "adulou", presente: "adula", futuro: "adulará" } },
  "adversidade": { classe: "substantivo", gravidade: null },
  "adverso": { classe: "adjetivo", gravidade: -1 },
  "afável": { classe: "adjetivo", gravidade: 2 },
  "afastar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "afastou", presente: "afasta", futuro: "afastará" } },
  "afetivo": { classe: "adjetivo", gravidade: 1 },
  "afiar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "afiou", presente: "afia", futuro: "afiará" } },
  "afinar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "afinou", presente: "afina", futuro: "afinará" } },
  "afirmação": { classe: "substantivo", gravidade: null },
  "afirmar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "afirmou", presente: "afirma", futuro: "afirmará" } },
  "aflito": { classe: "adjetivo", gravidade: -1 },
  "afligir": { classe: "verbo", gravidade: -2, conjugacao: { passado: "afligiu", presente: "aflige", futuro: "afligirá" } },
  "afluxo": { classe: "substantivo", gravidade: null },
  "afobar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "afobou", presente: "afoba", futuro: "afobará" } },
  "afogamento": { classe: "substantivo", gravidade: null },
  "afogar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "afogou", presente: "afoga", futuro: "afogará" } },
  "afrontar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "afrontou", presente: "afronta", futuro: "afrontará" } },
  "agachar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "agachou", presente: "agacha", futuro: "agachará" } },
  "agarrar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "agarrou", presente: "agarra", futuro: "agarrará" } },
  "agitar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "agitou", presente: "agita", futuro: "agitará" } },
  "agudizar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "agudizou", presente: "agudiza", futuro: "agudizará" } },
  "agora": { classe: "advérbio", gravidade: null },
  "agradável": { classe: "adjetivo", gravidade: 1 },
  "agradecer": { classe: "verbo", gravidade: 2, conjugacao: { passado: "agradeceu", presente: "agradece", futuro: "agradecerá" } },
  "agravamento": { classe: "substantivo", gravidade: null },
  "agravar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "agravou", presente: "agrava", futuro: "agravará" } },
  "agredir": { classe: "verbo", gravidade: -2, conjugacao: { passado: "agrediu", presente: "agride", futuro: "agredirá" } },
  "agressivo": { classe: "adjetivo", gravidade: -2 },
  "agricultura": { classe: "substantivo", gravidade: null },
  "água": { classe: "substantivo", gravidade: null },
  "aguentar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "aguentou", presente: "aguenta", futuro: "aguentará" } },
  "agulha": { classe: "substantivo", gravidade: null },
  "ai": { classe: "interjeição", gravidade: null },
  "ainda": { classe: "advérbio", gravidade: null },
  "ajudar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "ajudou", presente: "ajuda", futuro: "ajudará" } },
  "alarme": { classe: "substantivo", gravidade: null },
  "alcançar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "alcançou", presente: "alcança", futuro: "alcançará" } },
  "aldeia": { classe: "substantivo", gravidade: null },
  "alegrar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "alegrou", presente: "alegra", futuro: "alegrará" } },
  "alegre": { classe: "adjetivo", gravidade: 2 },
  "alerta": { classe: "adjetivo", gravidade: 0 },
  "alfaiate": { classe: "substantivo", gravidade: null },
  "algoritmo": { classe: "substantivo", gravidade: null },
  "alheio": { classe: "adjetivo", gravidade: 0 },
  "ali": { classe: "advérbio", gravidade: null },
  "alienar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "alienou", presente: "aliena", futuro: "alienará" } },
  "alimentar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "alimentou", presente: "alimenta", futuro: "alimentará" } },
  "alinhado": { classe: "adjetivo", gravidade: 1 },
  "aliviação": { classe: "substantivo", gravidade: null },
  "aliviar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "aliviou", presente: "alivia", futuro: "aliviará" } },
  "alma": { classe: "substantivo", gravidade: null },
  "almejar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "almejou", presente: "almeja", futuro: "almejará" } },
  "almoçar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "almoçou", presente: "almoça", futuro: "almoçará" } },
  "alpinismo": { classe: "substantivo", gravidade: null },
  "altanado": { classe: "adjetivo", gravidade: 1 },
  "alterar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "alterou", presente: "altera", futuro: "alterará" } },
  "alternar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "alternou", presente: "alterna", futuro: "alternará" } },
  "alto": { classe: "adjetivo", gravidade: 0 },
  "altruísta": { classe: "adjetivo", gravidade: 2 },
  "alucinar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "alucinou", presente: "alucina", futuro: "alucinará" } },
  "alugado": { classe: "adjetivo", gravidade: 0 },
  "alugar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "alugou", presente: "aluga", futuro: "alugará" } },
  "alvorada": { classe: "substantivo", gravidade: null },
  "amaldiçoar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "amaldiçoou", presente: "amaldiçoa", futuro: "amaldiçoará" } },
  "amargo": { classe: "adjetivo", gravidade: -1 },
  "amarrar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "amarrou", presente: "amarra", futuro: "amarrará" } },
  "amável": { classe: "adjetivo", gravidade: 2 },
  "ameaçar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "ameaçou", presente: "ameaça", futuro: "ameaçará" } },
  "ameno": { classe: "adjetivo", gravidade: 1 },
  "amigo": { classe: "substantivo", gravidade: null },
  "amizade": { classe: "substantivo", gravidade: null },
  "amortecer": { classe: "verbo", gravidade: 0, conjugacao: { passado: "amorteceu", presente: "amortece", futuro: "amortecerá" } },
  "ampliar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "ampliou", presente: "amplia", futuro: "ampliará" } },
  "análise": { classe: "substantivo", gravidade: null },
  "analisar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "analisou", presente: "analisa", futuro: "analisará" } },
  "ancorar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "ancorou", presente: "ancora", futuro: "ancorará" } },
  "andar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "andou", presente: "anda", futuro: "andará" } },
  "anedota": { classe: "substantivo", gravidade: null },
  "anel": { classe: "substantivo", gravidade: null },
  "anexo": { classe: "substantivo", gravidade: null },
  "anfitrião": { classe: "substantivo", gravidade: null },
  "animado": { classe: "adjetivo", gravidade: 1 },
  "animar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "animou", presente: "anima", futuro: "animará" } },
  "aniquilar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "aniquilou", presente: "aniquila", futuro: "aniquilará" } },
  "aniversário": { classe: "substantivo", gravidade: null },
  "anotado": { classe: "adjetivo", gravidade: 0 },
  "anotar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "anotou", presente: "anota", futuro: "anotará" } },
  "anseio": { classe: "substantivo", gravidade: null },
  "ansioso": { classe: "adjetivo", gravidade: -1 },
  "antagônico": { classe: "adjetivo", gravidade: -1 },
  "antepor": { classe: "verbo", gravidade: 0, conjugacao: { passado: "antepôs", presente: "antepõe", futuro: "anteporá" } },
  "antigo": { classe: "adjetivo", gravidade: 0 },
  "antipático": { classe: "adjetivo", gravidade: -2 },
  "anular": { classe: "verbo", gravidade: -1, conjugacao: { passado: "anulou", presente: "anula", futuro: "anulará" } },
  "anunciar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "anunciou", presente: "anuncia", futuro: "anunciará" } },
  "apagado": { classe: "adjetivo", gravidade: -1 },
  "apagar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "apagou", presente: "apaga", futuro: "apagará" } },
  "apaixonante": { classe: "adjetivo", gravidade: 2 },
  "apaixonar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "apaixonou", presente: "apaixona", futuro: "apaixonará" } },
  "apanhar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "apanhou", presente: "apanha", futuro: "apanhará" } },
  "apavorado": { classe: "adjetivo", gravidade: -2 },
  "apavorar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "apavorou", presente: "apavora", futuro: "apavorará" } },
  "apaziguar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "apaziguou", presente: "apazigua", futuro: "apaziguará" } },
  "apegar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "apegou", presente: "apega", futuro: "apegará" } },
  "aperto": { classe: "substantivo", gravidade: null },
  "apesar": { classe: "preposição", gravidade: null },
  "apetite": { classe: "substantivo", gravidade: null },
  "apitar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "apitou", presente: "apita", futuro: "apitará" } },
  "aplaca": { classe: "substantivo", gravidade: null },
  "atordoar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "atordou", presente: "atordoa", futuro: "atordoará" } },
  "apoiar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "apoiou", presente: "apoia", futuro: "apoiará" } },
  "apresentar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "apresentou", presente: "apresenta", futuro: "apresentará" } },
  "apressado": { classe: "adjetivo", gravidade: -1 },
  "apressar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "apressou", presente: "apressa", futuro: "apressará" } },
  "aprimorar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "aprimorou", presente: "aprimora", futuro: "aprimorará" } },
  "apropriado": { classe: "adjetivo", gravidade: 1 },
  "aprovar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "aprovou", presente: "aprova", futuro: "aprovará" } },
  "aproveitar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "aproveitou", presente: "aproveita", futuro: "aproveitará" } },
  "aproximar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "aproximou", presente: "aproxima", futuro: "aproximará" } },
  "aquecer": { classe: "verbo", gravidade: 1, conjugacao: { passado: "aqueceu", presente: "aquece", futuro: "aquecerá" } },
  "aquém": { classe: "advérbio", gravidade: null },
  "aqui": { classe: "advérbio", gravidade: null },
  "ar": { classe: "substantivo", gravidade: null },
  "arara": { classe: "substantivo", gravidade: null },
  "arbitrar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "arbitrou", presente: "arbitra", futuro: "arbitrará" } },
  "árvore": { classe: "substantivo", gravidade: null },
  "arcano": { classe: "adjetivo", gravidade: 0 },
  "ardiloso": { classe: "adjetivo", gravidade: -2 },
  "ardor": { classe: "substantivo", gravidade: null },
  "areia": { classe: "substantivo", gravidade: null },
  "arrogante": { classe: "adjetivo", gravidade: -2 },
  "arruinar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "arruinou", presente: "arruina", futuro: "arruinará" } },
  "artifício": { classe: "substantivo", gravidade: null },
  "árduo": { classe: "adjetivo", gravidade: -1 },
  "atordoado": { classe: "adjetivo", gravidade: -1 },
  "atroz": { classe: "adjetivo", gravidade: -2 },
  "audaz": { classe: "adjetivo", gravidade: 1 },
  "ausente": { classe: "adjetivo", gravidade: -1 },
  "autêntico": { classe: "adjetivo", gravidade: 2 },
  "avançar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "avançou", presente: "avança", futuro: "avançará" } },

  // B
  "batalha": { classe: "substantivo", gravidade: null },
  "babar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "babou", presente: "baba", futuro: "babará" } },
  "bagunçado": { classe: "adjetivo", gravidade: -1 },
  "bagunçar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "bagunçou", presente: "bagunça", futuro: "bagunçará" } },
  "bailar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "bailou", presente: "baila", futuro: "bailará" } },
  "baixo": { classe: "adjetivo", gravidade: 0 },
  "balançar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "balançou", presente: "balança", futuro: "balançará" } },
  "baluarte": { classe: "substantivo", gravidade: null },
  "banal": { classe: "adjetivo", gravidade: 0 },
  "banhar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "banhou", presente: "banha", futuro: "banhará" } },
  "banir": { classe: "verbo", gravidade: -2, conjugacao: { passado: "baniu", presente: "bane", futuro: "banirá" } },
  "barato": { classe: "adjetivo", gravidade: 1 },
  "barulho": { classe: "substantivo", gravidade: null },
  "bastante": { classe: "advérbio", gravidade: null },
  "bater": { classe: "verbo", gravidade: -1, conjugacao: { passado: "bateu", presente: "bate", futuro: "baterá" } },
  "beber": { classe: "verbo", gravidade: 0, conjugacao: { passado: "bebeu", presente: "bebe", futuro: "beberá" } },
  "beleza": { classe: "substantivo", gravidade: null },
  "belicoso": { classe: "adjetivo", gravidade: -2 },
  "belo": { classe: "adjetivo", gravidade: 2 },
  "bem": { classe: "advérbio", gravidade: null },
  "bendizer": { classe: "verbo", gravidade: 2, conjugacao: { passado: "bendisse", presente: "bendiz", futuro: "bendirá" } },
  "beneficiar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "beneficiou", presente: "beneficia", futuro: "beneficiará" } },
  "benévolo": { classe: "adjetivo", gravidade: 2 },
  "benigno": { classe: "adjetivo", gravidade: 2 },
  "bênção": { classe: "substantivo", gravidade: null },
  "bestial": { classe: "adjetivo", gravidade: -2 },
  "bizarro": { classe: "adjetivo", gravidade: -1 },
  "blasfemar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "blasfemou", presente: "blasfema", futuro: "blasfemará" } },
  "bloquear": { classe: "verbo", gravidade: -1, conjugacao: { passado: "bloqueou", presente: "bloqueia", futuro: "bloqueará" } },
  "boa": { classe: "adjetivo", gravidade: 1 },
  "bobagem": { classe: "substantivo", gravidade: null },
  "bobo": { classe: "adjetivo", gravidade: -1 },
  "boca": { classe: "substantivo", gravidade: null },
  "bom": { classe: "adjetivo", gravidade: 1 },
  "bondade": { classe: "substantivo", gravidade: null },
  "bondoso": { classe: "adjetivo", gravidade: 2 },
  "bonito": { classe: "adjetivo", gravidade: 1 },
  "bordo": { classe: "substantivo", gravidade: null },
  "borrasca": { classe: "substantivo", gravidade: null },
  "bosque": { classe: "substantivo", gravidade: null },
  "boto": { classe: "substantivo", gravidade: null },
  "bravura": { classe: "substantivo", gravidade: null },
  "bravo": { classe: "adjetivo", gravidade: 1 },
  "breve": { classe: "adjetivo", gravidade: 0 },
  "briga": { classe: "substantivo", gravidade: null },
  "brigar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "brigou", presente: "briga", futuro: "brigará" } },
  "brilhar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "brilhou", presente: "brilha", futuro: "brilhará" } },
  "brilhantismo": { classe: "substantivo", gravidade: null },
  "brincar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "brincou", presente: "brinca", futuro: "brincará" } },
  "brisa": { classe: "substantivo", gravidade: null },
  "bronze": { classe: "substantivo", gravidade: null },
  "bruto": { classe: "adjetivo", gravidade: -1 },
  "bruxa": { classe: "substantivo", gravidade: null },
  "burburinho": { classe: "substantivo", gravidade: null },
  "buscar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "buscou", presente: "busca", futuro: "buscará" } },

  // C
  "cabal": { classe: "adjetivo", gravidade: 1 },
  "cabeça": { classe: "substantivo", gravidade: null },
  "caber": { classe: "verbo", gravidade: 0, conjugacao: { passado: "coube", presente: "cabe", futuro: "caberá" } },
  "cacofonia": { classe: "substantivo", gravidade: null },
  "cada": { classe: "pronome", gravidade: null },
  "caderno": { classe: "substantivo", gravidade: null },
  "caduco": { classe: "adjetivo", gravidade: -1 },
  "cafezal": { classe: "substantivo", gravidade: null },
  "cair": { classe: "verbo", gravidade: -1, conjugacao: { passado: "caiu", presente: "cai", futuro: "cairá" } },
  "calado": { classe: "adjetivo", gravidade: 0 },
  "calar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "calou", presente: "cala", futuro: "calará" } },
  "calamidade": { classe: "substantivo", gravidade: null },
  "calcular": { classe: "verbo", gravidade: 0, conjugacao: { passado: "calculou", presente: "calcula", futuro: "calculará" } },
  "calma": { classe: "substantivo", gravidade: null },
  "calmo": { classe: "adjetivo", gravidade: 1 },
  "calor": { classe: "substantivo", gravidade: null },
  "calúnia": { classe: "substantivo", gravidade: null },
  "caminhar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "caminhou", presente: "caminha", futuro: "caminhará" } },
  "caminho": { classe: "substantivo", gravidade: null },
  "campeão": { classe: "substantivo", gravidade: null },
  "campo": { classe: "substantivo", gravidade: null },
  "cancelar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "cancelou", presente: "cancela", futuro: "cancelará" } },
  "cansaço": { classe: "substantivo", gravidade: null },
  "cansado": { classe: "adjetivo", gravidade: -1 },
  "cansar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "cansou", presente: "cansa", futuro: "cansará" } },
  "cantar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "cantou", presente: "canta", futuro: "cantará" } },
  "caos": { classe: "substantivo", gravidade: null },
  "caótico": { classe: "adjetivo", gravidade: -2 },
  "capaz": { classe: "adjetivo", gravidade: 1 },
  "capricho": { classe: "substantivo", gravidade: null },
  "capturar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "capturou", presente: "captura", futuro: "capturará" } },
  "carro": { classe: "substantivo", gravidade: null },
  "carregar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "carregou", presente: "carrega", futuro: "carregará" } },
  "carinho": { classe: "substantivo", gravidade: null },
  "carinhoso": { classe: "adjetivo", gravidade: 2 },
  "caro": { classe: "adjetivo", gravidade: -1 },
  "casa": { classe: "substantivo", gravidade: null },
  "casar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "casou", presente: "casa", futuro: "casará" } },
  "castigar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "castigou", presente: "castiga", futuro: "castigará" } },
  "castelo": { classe: "substantivo", gravidade: null },
  "cativar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "cativou", presente: "cativa", futuro: "cativará" } },
  "causa": { classe: "substantivo", gravidade: null },
  "causar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "causou", presente: "causa", futuro: "causará" } },
  "cautela": { classe: "substantivo", gravidade: null },
  "cauteloso": { classe: "adjetivo", gravidade: 1 },
  "cavalar": { classe: "adjetivo", gravidade: 0 },
  "ceder": { classe: "verbo", gravidade: 0, conjugacao: { passado: "cedeu", presente: "cede", futuro: "cederá" } },
  "celeste": { classe: "adjetivo", gravidade: 2 },
  "celebrio": { classe: "adjetivo", gravidade: 1 },
  "celebração": { classe: "substantivo", gravidade: null },
  "celebrar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "celebrou", presente: "celebra", futuro: "celebrará" } },
  "cérebro": { classe: "substantivo", gravidade: null },
  "certeza": { classe: "substantivo", gravidade: null },
  "certo": { classe: "adjetivo", gravidade: 1 },
  "cessar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "cessou", presente: "cessa", futuro: "cessará" } },
  "chama": { classe: "substantivo", gravidade: null },
  "chamar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "chamou", presente: "chama", futuro: "chamará" } },
  "chance": { classe: "substantivo", gravidade: null },
  "chato": { classe: "adjetivo", gravidade: -1 },
  "chegar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "chegou", presente: "chega", futuro: "chegará" } },
  "cheio": { classe: "adjetivo", gravidade: 0 },
  "cheiro": { classe: "substantivo", gravidade: null },
  "chorar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "chorou", presente: "chora", futuro: "chorará" } },
  "chuva": { classe: "substantivo", gravidade: null },
  "ciclo": { classe: "substantivo", gravidade: null },
  "cidade": { classe: "substantivo", gravidade: null },
  "ciência": { classe: "substantivo", gravidade: null },
  "cigano": { classe: "adjetivo", gravidade: 0 },
  "cima": { classe: "substantivo", gravidade: null },
  "cinema": { classe: "substantivo", gravidade: null },
  "cinza": { classe: "substantivo", gravidade: null },
  "ciúme": { classe: "substantivo", gravidade: null },
  "ciumento": { classe: "adjetivo", gravidade: -1 },
  "civilizado": { classe: "adjetivo", gravidade: 1 },
  "claridade": { classe: "substantivo", gravidade: null },
  "claro": { classe: "adjetivo", gravidade: 1 },
  "classe": { classe: "substantivo", gravidade: null },
  "clássico": { classe: "adjetivo", gravidade: 1 },
  "clementar": { classe: "adjetivo", gravidade: 1 },
  "cobrir": { classe: "verbo", gravidade: 0, conjugacao: { passado: "cobriu", presente: "cobre", futuro: "cobrirá" } },
  "coincidir": { classe: "verbo", gravidade: 0, conjugacao: { passado: "coincidiu", presente: "coincide", futuro: "coincidirá" } },
  "coisa": { classe: "substantivo", gravidade: null },
  "colaborar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "colaborou", presente: "colabora", futuro: "colaborará" } },
  "colapso": { classe: "substantivo", gravidade: null },
  "colega": { classe: "substantivo", gravidade: null },
  "coleta": { classe: "substantivo", gravidade: null },
  "colocar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "colocou", presente: "coloca", futuro: "colocará" } },
  "comandar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "comandou", presente: "comanda", futuro: "comandará" } },
  "combater": { classe: "verbo", gravidade: -1, conjugacao: { passado: "combateu", presente: "combate", futuro: "combaterá" } },
  "começar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "começou", presente: "começa", futuro: "começará" } },
  "comemorar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "comemorou", presente: "comemora", futuro: "comemorará" } },
  "comer": { classe: "verbo", gravidade: 0, conjugacao: { passado: "comeu", presente: "come", futuro: "comerá" } },
  "comercial": { classe: "adjetivo", gravidade: 0 },
  "cometer": { classe: "verbo", gravidade: -1, conjugacao: { passado: "cometeu", presente: "comete", futuro: "cometerá" } },
  "comigo": { classe: "pronome", gravidade: null },
  "como": { classe: "conjunção", gravidade: null },
  "compaixão": { classe: "substantivo", gravidade: null },
  "companha": { classe: "substantivo", gravidade: null },
  "comparar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "comparou", presente: "compara", futuro: "comparará" } },
  "compassivo": { classe: "adjetivo", gravidade: 2 },
  "competir": { classe: "verbo", gravidade: 0, conjugacao: { passado: "competiu", presente: "compete", futuro: "competirá" } },
  "complexo": { classe: "adjetivo", gravidade: -1 },
  "complicar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "complicou", presente: "complica", futuro: "complicará" } },
  "comprar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "comprou", presente: "compra", futuro: "comprará" } },
  "compreender": { classe: "verbo", gravidade: 2, conjugacao: { passado: "compreendeu", presente: "compreende", futuro: "compreenderá" } },
  "comum": { classe: "adjetivo", gravidade: 0 },
  "comunicar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "comunicou", presente: "comunica", futuro: "comunicará" } },
  "concordar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "concordou", presente: "concorda", futuro: "concordará" } },
  "condenar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "condenou", presente: "condena", futuro: "condenará" } },
  "conduzir": { classe: "verbo", gravidade: 0, conjugacao: { passado: "conduziu", presente: "conduz", futuro: "conduzirá" } },
  "conectar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "conectou", presente: "conecta", futuro: "conectará" } },
  "confiar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "confiou", presente: "confia", futuro: "confiará" } },
  "confuso": { classe: "adjetivo", gravidade: -1 },
  "conhecer": { classe: "verbo", gravidade: 1, conjugacao: { passado: "conheceu", presente: "conhece", futuro: "conhecerá" } },
  "conquistar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "conquistou", presente: "conquista", futuro: "conquistará" } },
  "construir": { classe: "verbo", gravidade: 2, conjugacao: { passado: "construiu", presente: "constrói", futuro: "construirá" } },
  "consumir": { classe: "verbo", gravidade: 0, conjugacao: { passado: "consumiu", presente: "consume", futuro: "consumirá" } },
  "contar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "contou", presente: "conta", futuro: "contará" } },
  "contemplar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "contemplou", presente: "contempla", futuro: "contemplará" } },
  "continuar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "continuou", presente: "continua", futuro: "continuará" } },
  "contra": { classe: "preposição", gravidade: null },
  "contribuição": { classe: "substantivo", gravidade: null },
  "convencer": { classe: "verbo", gravidade: 1, conjugacao: { passado: "convenceu", presente: "convence", futuro: "convencerá" } },
  "coragem": { classe: "substantivo", gravidade: null },
  "corajoso": { classe: "adjetivo", gravidade: 2 },
  "coração": { classe: "substantivo", gravidade: null },
  "cordial": { classe: "adjetivo", gravidade: 2 },
  "correr": { classe: "verbo", gravidade: 0, conjugacao: { passado: "correu", presente: "corre", futuro: "correrá" } },
  "corrigir": { classe: "verbo", gravidade: 1, conjugacao: { passado: "corrigiu", presente: "corrige", futuro: "corrigirá" } },
  "corromper": { classe: "verbo", gravidade: -2, conjugacao: { passado: "corrompeu", presente: "corrompe", futuro: "corromperá" } },
  "cortar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "cortou", presente: "corta", futuro: "cortará" } },
  "cortês": { classe: "adjetivo", gravidade: 1 },
  "covarde": { classe: "adjetivo", gravidade: -2 },
  "criar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "criou", presente: "cria", futuro: "criará" } },
  "crise": { classe: "substantivo", gravidade: null },
  "cruel": { classe: "adjetivo", gravidade: -2 },
  "cuidar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "cuidou", presente: "cuida", futuro: "cuidará" } },
  "culpar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "culpou", presente: "culpa", futuro: "culpará" } },
  "cultivar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "cultivou", presente: "cultiva", futuro: "cultivará" } },
  "curar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "curou", presente: "cura", futuro: "curará" } },
  "curioso": { classe: "adjetivo", gravidade: 1 },

  // D
  "dançar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "dançou", presente: "dança", futuro: "dançará" } },
  "danoso": { classe: "adjetivo", gravidade: -2 },
  "dantesco": { classe: "adjetivo", gravidade: -2 },
  "dar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "deu", presente: "dá", futuro: "dará" } },
  "debalde": { classe: "advérbio", gravidade: null },
  "decente": { classe: "adjetivo", gravidade: 1 },
  "decidir": { classe: "verbo", gravidade: 0, conjugacao: { passado: "decidiu", presente: "decide", futuro: "decidirá" } },
  "declarar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "declarou", presente: "declara", futuro: "declarará" } },
  "declinante": { classe: "adjetivo", gravidade: -1 },
  "decorrer": { classe: "verbo", gravidade: 0, conjugacao: { passado: "decorreu", presente: "decorre", futuro: "decorrerá" } },
  "decrepito": { classe: "adjetivo", gravidade: -2 },
  "dedicar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "dedicou", presente: "dedica", futuro: "dedicará" } },
  "defender": { classe: "verbo", gravidade: 1, conjugacao: { passado: "defendeu", presente: "defende", futuro: "defenderá" } },
  "definir": { classe: "verbo", gravidade: 0, conjugacao: { passado: "definiu", presente: "define", futuro: "definirá" } },
  "deplorável": { classe: "adjetivo", gravidade: -2 },
  "deitar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "deitou", presente: "deita", futuro: "deitará" } },
  "deixar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "deixou", presente: "deixa", futuro: "deixará" } },
  "deleite": { classe: "substantivo", gravidade: null },
  "delicado": { classe: "adjetivo", gravidade: 1 },
  "delícia": { classe: "substantivo", gravidade: null },
  "delicioso": { classe: "adjetivo", gravidade: 2 },
  "demonstrar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "demonstrou", presente: "demonstra", futuro: "demonstrará" } },
  "denso": { classe: "adjetivo", gravidade: 0 },
  "depender": { classe: "verbo", gravidade: 0, conjugacao: { passado: "dependeu", presente: "depende", futuro: "dependerá" } },
  "deprecar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "deprecou", presente: "depreca", futuro: "deprecará" } },
  "deprimido": { classe: "adjetivo", gravidade: -2 },
  "deprimir": { classe: "verbo", gravidade: -2, conjugacao: { passado: "deprimiu", presente: "deprime", futuro: "deprimirá" } },
  "derramar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "derramou", presente: "derrama", futuro: "derramará" } },
  "derrota": { classe: "substantivo", gravidade: null },
  "derrotar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "derrotou", presente: "derrota", futuro: "derrotará" } },
  "desafiar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "desafiou", presente: "desafia", futuro: "desafiará" } },
  "desafio": { classe: "substantivo", gravidade: null },
  "desagradável": { classe: "adjetivo", gravidade: -2 },
  "desanimado": { classe: "adjetivo", gravidade: -1 },
  "desarmar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "desarmou", presente: "desarma", futuro: "desarmará" } },
  "desastre": { classe: "substantivo", gravidade: null },
  "desastroso": { classe: "adjetivo", gravidade: -2 },
  "descansar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "descansou", presente: "descansa", futuro: "descansará" } },
  "descobrir": { classe: "verbo", gravidade: 1, conjugacao: { passado: "descobriu", presente: "descobre", futuro: "descobrirá" } },
  "desculpar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "desculpou", presente: "desculpa", futuro: "desculpará" } },
  "desejar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "desejou", presente: "deseja", futuro: "desejará" } },
  "desenvolver": { classe: "verbo", gravidade: 1, conjugacao: { passado: "desenvolveu", presente: "desenvolve", futuro: "desenvolverá" } },
  "desespero": { classe: "substantivo", gravidade: null },
  "desgraça": { classe: "substantivo", gravidade: null },
  "deslumbrante": { classe: "adjetivo", gravidade: 2 },
  "desperdiçar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "desperdiçou", presente: "desperdiça", futuro: "desperdiçará" } },
  "despertar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "despertou", presente: "desperta", futuro: "despertará" } },
  "destruir": { classe: "verbo", gravidade: -2, conjugacao: { passado: "destruiu", presente: "destrói", futuro: "destruirá" } },
  "detestar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "detestou", presente: "detesta", futuro: "detestará" } },
  "dever": { classe: "verbo", gravidade: 0, conjugacao: { passado: "deveu", presente: "deve", futuro: "deverá" } },
  "dia": { classe: "substantivo", gravidade: null },
  "diferente": { classe: "adjetivo", gravidade: 0 },
  "difícil": { classe: "adjetivo", gravidade: -1 },
  "digno": { classe: "adjetivo", gravidade: 2 },
  "diminuir": { classe: "verbo", gravidade: -1, conjugacao: { passado: "diminuiu", presente: "diminui", futuro: "diminuirá" } },
  "dinheiro": { classe: "substantivo", gravidade: null },
  "direito": { classe: "adjetivo", gravidade: 1 },
  "direto": { classe: "adjetivo", gravidade: 0 },
  "discutir": { classe: "verbo", gravidade: -1, conjugacao: { passado: "discutiu", presente: "discute", futuro: "discutirá" } },
  "distante": { classe: "adjetivo", gravidade: 0 },
  "divino": { classe: "adjetivo", gravidade: 2 },
  "dividir": { classe: "verbo", gravidade: 0, conjugacao: { passado: "dividiu", presente: "divide", futuro: "dividirá" } },
  "dizer": { classe: "verbo", gravidade: 0, conjugacao: { passado: "disse", presente: "diz", futuro: "dirá" } },
  "doce": { classe: "adjetivo", gravidade: 1 },
  "doença": { classe: "substantivo", gravidade: null },
  "doer": { classe: "verbo", gravidade: -1, conjugacao: { passado: "doeceu", presente: "dói", futuro: "doerá" } },
  "dor": { classe: "substantivo", gravidade: null },
  "dormir": { classe: "verbo", gravidade: 1, conjugacao: { passado: "dormiu", presente: "dorme", futuro: "dormirá" } },
  "dúvida": { classe: "substantivo", gravidade: null },
  "duvidar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "duvidou", presente: "duvida", futuro: "duvidará" } },

  // E
  "ecoar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "ecoou", presente: "ecoa", futuro: "ecoará" } },
  "educado": { classe: "adjetivo", gravidade: 1 },
  "efêmero": { classe: "adjetivo", gravidade: 0 },
  "eficaz": { classe: "adjetivo", gravidade: 1 },
  "eficiente": { classe: "adjetivo", gravidade: 1 },
  "egoísta": { classe: "adjetivo", gravidade: -2 },
  "elegante": { classe: "adjetivo", gravidade: 1 },
  "elevar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "elevou", presente: "eleva", futuro: "elevará" } },
  "elogiar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "elogiou", presente: "elogia", futuro: "elogiará" } },
  "emagrecer": { classe: "verbo", gravidade: 0, conjugacao: { passado: "emagreceu", presente: "emagrece", futuro: "emagrecerá" } },
  "emanar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "emanou", presente: "emana", futuro: "emanará" } },
  "emblema": { classe: "substantivo", gravidade: null },
  "embora": { classe: "conjunção", gravidade: null },
  "emoção": { classe: "substantivo", gravidade: null },
  "emocionante": { classe: "adjetivo", gravidade: 2 },
  "empatia": { classe: "substantivo", gravidade: null },
  "empoderar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "empoderou", presente: "empodera", futuro: "empoderará" } },
  "empregar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "empregou", presente: "emprega", futuro: "empregará" } },
  "encantar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "encantou", presente: "encanta", futuro: "encantará" } },
  "encarar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "encarou", presente: "encara", futuro: "encarará" } },
  "encorajar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "encorajou", presente: "encoraja", futuro: "encorajará" } },
  "encontrar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "encontrou", presente: "encontra", futuro: "encontrará" } },
  "energia": { classe: "substantivo", gravidade: null },
  "enfermo": { classe: "adjetivo", gravidade: -2 },
  "enganar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "enganou", presente: "engana", futuro: "enganará" } },
  "enigma": { classe: "substantivo", gravidade: null },
  "igmático": { classe: "adjetivo", gravidade: 0 },
  "enorme": { classe: "adjetivo", gravidade: 0 },
  "enriquecer": { classe: "verbo", gravidade: 1, conjugacao: { passado: "enriqueceu", presente: "enriquece", futuro: "enriquecerá" } },
  "ensinar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "ensinou", presente: "ensina", futuro: "ensinará" } },
  "entender": { classe: "verbo", gravidade: 1, conjugacao: { passado: "entendeu", presente: "entende", futuro: "entenderá" } },
  "entusiasmo": { classe: "substantivo", gravidade: null },
  "envolver": { classe: "verbo", gravidade: 0, conjugacao: { passado: "envolveu", presente: "envolve", futuro: "envolverá" } },
  "epifania": { classe: "substantivo", gravidade: null },
  "épico": { classe: "adjetivo", gravidade: 2 },
  "equilíbrio": { classe: "substantivo", gravidade: null },
  "equilibrado": { classe: "adjetivo", gravidade: 1 },
  "errar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "errou", presente: "erra", futuro: "errará" } },
  "erro": { classe: "substantivo", gravidade: null },
  "erudito": { classe: "adjetivo", gravidade: 1 },
  "escala": { classe: "substantivo", gravidade: null },
  "escapar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "escapou", presente: "escapa", futuro: "escapará" } },
  "esclarecer": { classe: "verbo", gravidade: 1, conjugacao: { passado: "esclareceu", presente: "esclarece", futuro: "esclarecerá" } },
  "esconder": { classe: "verbo", gravidade: 0, conjugacao: { passado: "escondeu", presente: "esconde", futuro: "esconderá" } },
  "escuro": { classe: "adjetivo", gravidade: -1 },
  "escutar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "escutou", presente: "escuta", futuro: "escutará" } },
  "esforçar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "esforçou", presente: "esforça", futuro: "esforçará" } },
  "esmerado": { classe: "adjetivo", gravidade: 2 },
  "espaço": { classe: "substantivo", gravidade: null },
  "esperança": { classe: "substantivo", gravidade: null },
  "esperar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "esperou", presente: "espera", futuro: "esperará" } },
  "esperto": { classe: "adjetivo", gravidade: 1 },
  "esplêndido": { classe: "adjetivo", gravidade: 2 },
  "esquecer": { classe: "verbo", gravidade: -1, conjugacao: { passado: "esqueceu", presente: "esquece", futuro: "esquecerá" } },
  "essencial": { classe: "adjetivo", gravidade: 1 },
  "estável": { classe: "adjetivo", gravidade: 1 },
  "estimar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "estimou", presente: "estima", futuro: "estimará" } },
  "estrela": { classe: "substantivo", gravidade: null },
  "estudar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "estudou", presente: "estuda", futuro: "estudará" } },
  "eterno": { classe: "adjetivo", gravidade: 1 },
  "eufórico": { classe: "adjetivo", gravidade: 2 },
  "evoluir": { classe: "verbo", gravidade: 2, conjugacao: { passado: "evoluiu", presente: "evolui", futuro: "evoluirá" } },
  "excelente": { classe: "adjetivo", gravidade: 2 },
  "excepcional": { classe: "adjetivo", gravidade: 2 },
  "exigir": { classe: "verbo", gravidade: -1, conjugacao: { passado: "exigiu", presente: "exige", futuro: "exigirá" } },
  "existir": { classe: "verbo", gravidade: 0, conjugacao: { passado: "existiu", presente: "existe", futuro: "existirá" } },
  "êxito": { classe: "substantivo", gravidade: null },
  "expandir": { classe: "verbo", gravidade: 1, conjugacao: { passado: "expandiu", presente: "expande", futuro: "expandirá" } },
  "explorar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "explorou", presente: "explora", futuro: "explorará" } },
  "expressar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "expressou", presente: "expressa", futuro: "expressará" } },
  "exuberante": { classe: "adjetivo", gravidade: 2 },

  // F
  "fábula": { classe: "substantivo", gravidade: null },
  "fácil": { classe: "adjetivo", gravidade: 1 },
  "falar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "falou", presente: "fala", futuro: "falará" } },
  "falhar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "falhou", presente: "falha", futuro: "falhará" } },
  "falha": { classe: "substantivo", gravidade: null },
  "falso": { classe: "adjetivo", gravidade: -2 },
  "fama": { classe: "substantivo", gravidade: null },
  "família": { classe: "substantivo", gravidade: null },
  "fantástico": { classe: "adjetivo", gravidade: 2 },
  "fardo": { classe: "substantivo", gravidade: null },
  "fascinar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "fascinou", presente: "fascina", futuro: "fascinará" } },
  "fatia": { classe: "substantivo", gravidade: null },
  "fazer": { classe: "verbo", gravidade: 0, conjugacao: { passado: "fez", presente: "faz", futuro: "fará" } },
  "firme": { classe: "adjetivo", gravidade: 1 },
  "fidelidade": { classe: "substantivo", gravidade: null },
  "fiel": { classe: "adjetivo", gravidade: 2 },
  "figura": { classe: "substantivo", gravidade: null },
  "fingir": { classe: "verbo", gravidade: -1, conjugacao: { passado: "fingiu", presente: "finge", futuro: "fingirá" } },
  "firmeza": { classe: "substantivo", gravidade: null },
  "flagelar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "flagelou", presente: "flagela", futuro: "flagelará" } },
  "flor": { classe: "substantivo", gravidade: null },
  "fluir": { classe: "verbo", gravidade: 1, conjugacao: { passado: "fluiu", presente: "flui", futuro: "fluirá" } },
  "fogo": { classe: "substantivo", gravidade: null },
  "formidável": { classe: "adjetivo", gravidade: 2 },
  "fortalecer": { classe: "verbo", gravidade: 2, conjugacao: { passado: "fortaleceu", presente: "fortalece", futuro: "fortalecerá" } },
  "forte": { classe: "adjetivo", gravidade: 1 },
  "fracassar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "fracassou", presente: "fracassa", futuro: "fracassará" } },
  "fraco": { classe: "adjetivo", gravidade: -1 },
  "frágil": { classe: "adjetivo", gravidade: -1 },
  "frio": { classe: "adjetivo", gravidade: 0 },
  "frustrar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "frustrou", presente: "frustra", futuro: "frustrará" } },
  "fuga": { classe: "substantivo", gravidade: null },
  "fugir": { classe: "verbo", gravidade: -1, conjugacao: { passado: "fugiu", presente: "foge", futuro: "fugirá" } },
  "furo": { classe: "substantivo", gravidade: null },
  "futurologia": { classe: "substantivo", gravidade: null },

  // G
  "ganhar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "ganhou", presente: "ganha", futuro: "ganhará" } },
  "garantia": { classe: "substantivo", gravidade: null },
  "generoso": { classe: "adjetivo", gravidade: 2 },
  "gentil": { classe: "adjetivo", gravidade: 2 },
  "gerar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "gerou", presente: "gera", futuro: "gerará" } },
  "gigante": { classe: "adjetivo", gravidade: 1 },
  "glorificar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "glorificou", presente: "glorifica", futuro: "glorificará" } },
  "gostoso": { classe: "adjetivo", gravidade: 1 },
  "grande": { classe: "adjetivo", gravidade: 0 },
  "grato": { classe: "adjetivo", gravidade: 2 },
  "grave": { classe: "adjetivo", gravidade: -2 },
  "grito": { classe: "substantivo", gravidade: null },
  "guardar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "guardou", presente: "guarda", futuro: "guardará" } },
  "guiar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "guiou", presente: "guia", futuro: "guiará" } },

  // H
  "hábil": { classe: "adjetivo", gravidade: 1 },
  "habitar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "habitou", presente: "habita", futuro: "habitará" } },
  "harmonioso": { classe: "adjetivo", gravidade: 2 },
  "hesitar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "hesitou", presente: "hesita", futuro: "hesitará" } },
  "história": { classe: "substantivo", gravidade: null },
  "hoje": { classe: "advérbio", gravidade: null },
  "holocausto": { classe: "substantivo", gravidade: null },
  "honesto": { classe: "adjetivo", gravidade: 2 },
  "honrar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "honrou", presente: "honra", futuro: "honrará" } },
  "horroroso": { classe: "adjetivo", gravidade: -2 },
  "hostil": { classe: "adjetivo", gravidade: -2 },
  "humilde": { classe: "adjetivo", gravidade: 1 },

  // I
  "ideal": { classe: "adjetivo", gravidade: 2 },
  "ideia": { classe: "substantivo", gravidade: null },
  "ignorar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "ignorou", presente: "ignora", futuro: "ignorará" } },
  "igual": { classe: "adjetivo", gravidade: 0 },
  "iluminar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "iluminou", presente: "ilumina", futuro: "iluminará" } },
  "ilusão": { classe: "substantivo", gravidade: null },
  "ilustre": { classe: "adjetivo", gravidade: 2 },
  "imaginar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "imaginou", presente: "imagina", futuro: "imaginará" } },
  "impacto": { classe: "substantivo", gravidade: null },
  "impecável": { classe: "adjetivo", gravidade: 2 },
  "impedir": { classe: "verbo", gravidade: -1, conjugacao: { passado: "impediu", presente: "impede", futuro: "impedirá" } },
  "imperfeito": { classe: "adjetivo", gravidade: -1 },
  "importante": { classe: "adjetivo", gravidade: 1 },
  "impor": { classe: "verbo", gravidade: -1, conjugacao: { passado: "impôs", presente: "impõe", futuro: "imporá" } },
  "impossível": { classe: "adjetivo", gravidade: -1 },
  "impressionar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "impressionou", presente: "impressiona", futuro: "impressionará" } },
  "incrível": { classe: "adjetivo", gravidade: 2 },
  "indicativo": { classe: "adjetivo", gravidade: 0 },
  "indiferente": { classe: "adjetivo", gravidade: -1 },
  "infernal": { classe: "adjetivo", gravidade: -2 },
  "infinito": { classe: "adjetivo", gravidade: 1 },
  "informar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "informou", presente: "informa", futuro: "informará" } },
  "injusto": { classe: "adjetivo", gravidade: -2 },
  "inovar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "inovou", presente: "inova", futuro: "inovará" } },
  "inspiração": { classe: "substantivo", gravidade: null },
  "inspirar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "inspirou", presente: "inspira", futuro: "inspirará" } },
  "inteligente": { classe: "adjetivo", gravidade: 2 },
  "intenso": { classe: "adjetivo", gravidade: 0 },
  "interessante": { classe: "adjetivo", gravidade: 1 },
  "inútil": { classe: "adjetivo", gravidade: -2 },
  "inveja": { classe: "substantivo", gravidade: null },
  "invejoso": { classe: "adjetivo", gravidade: -2 },
  "inverter": { classe: "verbo", gravidade: 0, conjugacao: { passado: "inverteu", presente: "inverte", futuro: "inverterá" } },
  "investir": { classe: "verbo", gravidade: 1, conjugacao: { passado: "investiu", presente: "investe", futuro: "investirá" } },
  "ir": { classe: "verbo", gravidade: 0, conjugacao: { passado: "foi", presente: "vai", futuro: "irá" } },
  "isolar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "isolou", presente: "isola", futuro: "isolará" } },

  // J
  "jamais": { classe: "advérbio", gravidade: null },
  "janela": { classe: "substantivo", gravidade: null },
  "jardim": { classe: "substantivo", gravidade: null },
  "jocoso": { classe: "adjetivo", gravidade: 1 },
  "jogar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "jogou", presente: "joga", futuro: "jogará" } },
  "jovem": { classe: "adjetivo", gravidade: 0 },
  "júbilo": { classe: "substantivo", gravidade: null },
  "jugar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "jugou", presente: "juga", futuro: "jugará" } },
  "julgamento": { classe: "substantivo", gravidade: null },
  "julgar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "julgou", presente: "julga", futuro: "julgará" } },
  "juntar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "juntou", presente: "junta", futuro: "juntará" } },
  "jurar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "jurou", presente: "jura", futuro: "jurará" } },
  "justo": { classe: "adjetivo", gravidade: 2 },
  "juventude": { classe: "substantivo", gravidade: null },

  // K
  "kafkiano": { classe: "adjetivo", gravidade: -1 },
  "ketchup": { classe: "substantivo", gravidade: null },
  "kilobyte": { classe: "substantivo", gravidade: null },
  "kiwi": { classe: "substantivo", gravidade: null },

  // L
  "labirinto": { classe: "substantivo", gravidade: null },
  "lamentar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "lamentou", presente: "lamenta", futuro: "lamentará" } },
  "lançar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "lançou", presente: "lança", futuro: "lançará" } },
  "largo": { classe: "adjetivo", gravidade: 0 },
  "lágrima": { classe: "substantivo", gravidade: null },
  "leal": { classe: "adjetivo", gravidade: 2 },
  "lembrar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "lembrou", presente: "lembra", futuro: "lembrará" } },
  "lento": { classe: "adjetivo", gravidade: -1 },
  "ler": { classe: "verbo", gravidade: 1, conjugacao: { passado: "leu", presente: "lê", futuro: "lerá" } },
  "lealdade": { classe: "substantivo", gravidade: null },
  "libertar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "libertou", presente: "liberta", futuro: "libertará" } },
  "livre": { classe: "adjetivo", gravidade: 2 },
  "limpar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "limpou", presente: "limpa", futuro: "limpará" } },
  "lindo": { classe: "adjetivo", gravidade: 2 },
  "líquido": { classe: "substantivo", gravidade: null },
  "liso": { classe: "adjetivo", gravidade: 0 },
  "livro": { classe: "substantivo", gravidade: null },
  "luz": { classe: "substantivo", gravidade: null },
  "lugar": { classe: "substantivo", gravidade: null },
  "lúgubre": { classe: "adjetivo", gravidade: -2 },
  "lutar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "lutou", presente: "luta", futuro: "lutará" } },

  // M
  "macio": { classe: "adjetivo", gravidade: 1 },
  "magnânimo": { classe: "adjetivo", gravidade: 2 },
  "magnífico": { classe: "adjetivo", gravidade: 2 },
  "magoar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "magoou", presente: "magoa", futuro: "magoará" } },
  "maior": { classe: "adjetivo", gravidade: 1 },
  "mal": { classe: "advérbio", gravidade: null },
  "maldoso": { classe: "adjetivo", gravidade: -2 },
  "maléfico": { classe: "adjetivo", gravidade: -2 },
  "manter": { classe: "verbo", gravidade: 1, conjugacao: { passado: "manteve", presente: "mantém", futuro: "manterá" } },
  "maravilhoso": { classe: "adjetivo", gravidade: 2 },
  "marcar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "marcou", presente: "marca", futuro: "marcará" } },
  "medo": { classe: "substantivo", gravidade: null },
  "melhor": { classe: "adjetivo", gravidade: 2 },
  "melhorar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "melhorou", presente: "melhora", futuro: "melhorará" } },
  "mentir": { classe: "verbo", gravidade: -2, conjugacao: { passado: "mentiu", presente: "mente", futuro: "mentirá" } },
  "mesmo": { classe: "adjetivo", gravidade: 0 },
  "mestre": { classe: "substantivo", gravidade: null },
  "meta": { classe: "substantivo", gravidade: null },
  "mudar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "mudou", presente: "muda", futuro: "mudará" } },
  "muito": { classe: "advérbio", gravidade: null },
  "mundo": { classe: "substantivo", gravidade: null },
  "mutilar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "mutilou", presente: "mutila", futuro: "mutilará" } },

  // N
  "nascer": { classe: "verbo", gravidade: 2, conjugacao: { passado: "nasceu", presente: "nasce", futuro: "nascerá" } },
  "natureza": { classe: "substantivo", gravidade: null },
  "navegar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "navegou", presente: "navega", futuro: "navegará" } },
  "nefasto": { classe: "adjetivo", gravidade: -2 },
  "negar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "negou", presente: "nega", futuro: "negará" } },
  "negativo": { classe: "adjetivo", gravidade: -1 },
  "negócio": { classe: "substantivo", gravidade: null },
  "neve": { classe: "substantivo", gravidade: null },
  "noite": { classe: "substantivo", gravidade: null },
  "nome": { classe: "substantivo", gravidade: null },
  "norma": { classe: "substantivo", gravidade: null },
  "normal": { classe: "adjetivo", gravidade: 0 },
  "notável": { classe: "adjetivo", gravidade: 2 },
  "novo": { classe: "adjetivo", gravidade: 1 },
  "nuvem": { classe: "substantivo", gravidade: null },

  // O
  "obedecer": { classe: "verbo", gravidade: 1, conjugacao: { passado: "obedeceu", presente: "obedece", futuro: "obedecerá" } },
  "objetivo": { classe: "substantivo", gravidade: null },
  "obrigar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "obrigou", presente: "obriga", futuro: "obrigará" } },
  "observar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "observou", presente: "observa", futuro: "observará" } },
  "obter": { classe: "verbo", gravidade: 1, conjugacao: { passado: "obteve", presente: "obtém", futuro: "obterá" } },
  "oculto": { classe: "adjetivo", gravidade: 0 },
  "ofender": { classe: "verbo", gravidade: -2, conjugacao: { passado: "ofendeu", presente: "ofende", futuro: "ofenderá" } },
  "olhar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "olhou", presente: "olha", futuro: "olhará" } },
  "ominoso": { classe: "adjetivo", gravidade: -2 },
  "oprimir": { classe: "verbo", gravidade: -2, conjugacao: { passado: "oprimiu", presente: "oprime", futuro: "oprimirá" } },
  "orgulho": { classe: "substantivo", gravidade: null },
  "otimista": { classe: "adjetivo", gravidade: 1 },
  "ouvir": { classe: "verbo", gravidade: 0, conjugacao: { passado: "ouviu", presente: "ouve", futuro: "ouvirá" } },

  // P
  "paciente": { classe: "adjetivo", gravidade: 2 },
  "pagar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "pagou", presente: "paga", futuro: "pagará" } },
  "palavra": { classe: "substantivo", gravidade: null },
  "parar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "parou", presente: "para", futuro: "parará" } },
  "parecer": { classe: "verbo", gravidade: 0, conjugacao: { passado: "pareceu", presente: "parece", futuro: "parecerá" } },
  "partir": { classe: "verbo", gravidade: 0, conjugacao: { passado: "partiu", presente: "parte", futuro: "partirá" } },
  "passar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "passou", presente: "passa", futuro: "passará" } },
  "paz": { classe: "substantivo", gravidade: null },
  "pedir": { classe: "verbo", gravidade: 0, conjugacao: { passado: "pediu", presente: "pede", futuro: "pedirá" } },
  "pensar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "pensou", presente: "pensa", futuro: "pensará" } },
  "perder": { classe: "verbo", gravidade: -1, conjugacao: { passado: "perdeu", presente: "perde", futuro: "perderá" } },
  "perdoar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "perdoou", presente: "perdoa", futuro: "perdoará" } },
  "perfeito": { classe: "adjetivo", gravidade: 2 },
  "péssimo": { classe: "adjetivo", gravidade: -2 },
  "poder": { classe: "verbo", gravidade: 1, conjugacao: { passado: "pôde", presente: "pode", futuro: "poderá" } },
  "por": { classe: "verbo", gravidade: 0, conjugacao: { passado: "pôs", presente: "põe", futuro: "porá" } },
  "precisar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "precisou", presente: "precisa", futuro: "precisará" } },
  "prejudicar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "prejudicou", presente: "prejudica", futuro: "prejudicará" } },
  "prosperar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "prosperou", presente: "prospera", futuro: "prosperará" } },
  "puro": { classe: "adjetivo", gravidade: 1 },

  // Q
  "qualidade": { classe: "substantivo", gravidade: null },
  "qualquer": { classe: "pronome", gravidade: null },
  "quando": { classe: "advérbio", gravidade: null },
  "quente": { classe: "adjetivo", gravidade: 0 },
  "querer": { classe: "verbo", gravidade: 1, conjugacao: { passado: "quis", presente: "quer", futuro: "quererá" } },
  "quieto": { classe: "adjetivo", gravidade: 0 },
  "quimérico": { classe: "adjetivo", gravidade: 0 },
  "quitar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "quitou", presente: "quita", futuro: "quitará" } },

  // R
  "radiante": { classe: "adjetivo", gravidade: 2 },
  "raiva": { classe: "substantivo", gravidade: null },
  "ramo": { classe: "substantivo", gravidade: null },
  "rápido": { classe: "adjetivo", gravidade: 1 },
  "raro": { classe: "adjetivo", gravidade: 1 },
  "razão": { classe: "substantivo", gravidade: null },
  "realizar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "realizou", presente: "realiza", futuro: "realizará" } },
  "receber": { classe: "verbo", gravidade: 1, conjugacao: { passado: "recebeu", presente: "recebe", futuro: "receberá" } },
  "reconhecer": { classe: "verbo", gravidade: 1, conjugacao: { passado: "reconheceu", presente: "reconhece", futuro: "reconhecerá" } },
  "recusar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "recusou", presente: "recusa", futuro: "recusará" } },
  "reduzir": { classe: "verbo", gravidade: -1, conjugacao: { passado: "reduziu", presente: "reduz", futuro: "reduzirá" } },
  "regressar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "regressou", presente: "regressa", futuro: "regressará" } },
  "reinar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "reinou", presente: "reina", futuro: "reinará" } },
  "renovar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "renovou", presente: "renova", futuro: "renovará" } },
  "respeitar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "respeitou", presente: "respeita", futuro: "respeitará" } },
  "responder": { classe: "verbo", gravidade: 0, conjugacao: { passado: "respondeu", presente: "responde", futuro: "responderá" } },
  "rir": { classe: "verbo", gravidade: 1, conjugacao: { passado: "riu", presente: "ri", futuro: "rirá" } },
  "roubar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "roubou", presente: "rouba", futuro: "roubará" } },
  "ruim": { classe: "adjetivo", gravidade: -1 },
  "ruir": { classe: "verbo", gravidade: -2, conjugacao: { passado: "ruiu", presente: "rui", futuro: "ruirá" } },

  // S
  "saber": { classe: "verbo", gravidade: 1, conjugacao: { passado: "soube", presente: "sabe", futuro: "saberá" } },
  "sabedoria": { classe: "substantivo", gravidade: null },
  "sábio": { classe: "adjetivo", gravidade: 2 },
  "sacrifício": { classe: "substantivo", gravidade: null },
  "sair": { classe: "verbo", gravidade: 0, conjugacao: { passado: "saiu", presente: "sai", futuro: "sairá" } },
  "salvar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "salvou", presente: "salva", futuro: "salvará" } },
  "saúde": { classe: "substantivo", gravidade: null },
  "seguro": { classe: "adjetivo", gravidade: 1 },
  "sempre": { classe: "advérbio", gravidade: null },
  "sentir": { classe: "verbo", gravidade: 0, conjugacao: { passado: "sentiu", presente: "sente", futuro: "sentirá" } },
  "ser": { classe: "verbo", gravidade: 0, conjugacao: { passado: "foi", presente: "é", futuro: "será" } },
  "severo": { classe: "adjetivo", gravidade: -1 },
  "silêncio": { classe: "substantivo", gravidade: null },
  "simpático": { classe: "adjetivo", gravidade: 1 },
  "sóbrio": { classe: "adjetivo", gravidade: 0 },
  "socorrer": { classe: "verbo", gravidade: 2, conjugacao: { passado: "socorreu", presente: "socorre", futuro: "socorrerá" } },
  "sol": { classe: "substantivo", gravidade: null },
  "solitário": { classe: "adjetivo", gravidade: -1 },
  "sonhar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "sonhou", presente: "sonha", futuro: "sonhará" } },
  "sorrir": { classe: "verbo", gravidade: 1, conjugacao: { passado: "sorriu", presente: "sorri", futuro: "sorrirá" } },
  "sublime": { classe: "adjetivo", gravidade: 2 },
  "sucesso": { classe: "substantivo", gravidade: null },
  "superar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "superou", presente: "supera", futuro: "superará" } },

  // T
  "talento": { classe: "substantivo", gravidade: null },
  "talentoso": { classe: "adjetivo", gravidade: 2 },
  "também": { classe: "advérbio", gravidade: null },
  "tarde": { classe: "substantivo", gravidade: null },
  "tempestade": { classe: "substantivo", gravidade: null },
  "tempo": { classe: "substantivo", gravidade: null },
  "tentar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "tentou", presente: "tenta", futuro: "tentará" } },
  "ter": { classe: "verbo", gravidade: 0, conjugacao: { passado: "teve", presente: "tem", futuro: "terá" } },
  "terrivel": { classe: "adjetivo", gravidade: -2 },
  "tímido": { classe: "adjetivo", gravidade: -1 },
  "tirar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "tirou", presente: "tira", futuro: "tirará" } },
  "tocar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "tocou", presente: "toca", futuro: "tocará" } },
  "tomar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "tomou", presente: "toma", futuro: "tomará" } },
  "trabalhar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "trabalhou", presente: "trabalha", futuro: "trabalhará" } },
  "trágico": { classe: "adjetivo", gravidade: -2 },
  "transformar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "transformou", presente: "transforma", futuro: "transformará" } },
  "trazer": { classe: "verbo", gravidade: 0, conjugacao: { passado: "trouxe", presente: "traz", futuro: "trará" } },
  "triste": { classe: "adjetivo", gravidade: -1 },
  "triunfar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "triunfou", presente: "triunfa", futuro: "triunfará" } },
  "tudo": { classe: "pronome", gravidade: null },

  // U
  "último": { classe: "adjetivo", gravidade: 0 },
  "único": { classe: "adjetivo", gravidade: 1 },
  "unir": { classe: "verbo", gravidade: 2, conjugacao: { passado: "uniu", presente: "une", futuro: "unirá" } },
  "universo": { classe: "substantivo", gravidade: null },
  "urgente": { classe: "adjetivo", gravidade: -1 },
  "usar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "usou", presente: "usa", futuro: "usará" } },
  "usurpar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "usurpou", presente: "usurpa", futuro: "usurpará" } },
  "útil": { classe: "adjetivo", gravidade: 1 },
  "utilitário": { classe: "adjetivo", gravidade: 0 },
  "utópico": { classe: "adjetivo", gravidade: 1 },

  // V
  "vazio": { classe: "adjetivo", gravidade: -1 },
  "valioso": { classe: "adjetivo", gravidade: 2 },
  "valor": { classe: "substantivo", gravidade: null },
  "vencer": { classe: "verbo", gravidade: 2, conjugacao: { passado: "venceu", presente: "vence", futuro: "vencerá" } },
  "vender": { classe: "verbo", gravidade: 0, conjugacao: { passado: "vendeu", presente: "vende", futuro: "venderá" } },
  "venerar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "venerou", presente: "venera", futuro: "venerará" } },
  "vento": { classe: "substantivo", gravidade: null },
  "ver": { classe: "verbo", gravidade: 0, conjugacao: { passado: "viu", presente: "vê", futuro: "verá" } },
  "verdade": { classe: "substantivo", gravidade: null },
  "verdadeiro": { classe: "adjetivo", gravidade: 2 },
  "vermelho": { classe: "adjetivo", gravidade: 0 },
  "vestir": { classe: "verbo", gravidade: 0, conjugacao: { passado: "vestiu", presente: "veste", futuro: "vestirá" } },
  "vida": { classe: "substantivo", gravidade: null },
  "viver": { classe: "verbo", gravidade: 2, conjugacao: { passado: "viveu", presente: "vive", futuro: "viverá" } },
  "voar": { classe: "verbo", gravidade: 1, conjugacao: { passado: "voou", presente: "voa", futuro: "voará" } },
  "voltar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "voltou", presente: "volta", futuro: "voltará" } },

  // W
  "wafer": { classe: "substantivo", gravidade: null },
  "waffle": { classe: "substantivo", gravidade: null },
  "webcam": { classe: "substantivo", gravidade: null },
  "wifi": { classe: "substantivo", gravidade: null },

  // X
  "xadrez": { classe: "substantivo", gravidade: null },
  "xale": { classe: "substantivo", gravidade: null },
  "xampu": { classe: "substantivo", gravidade: null },
  "xarope": { classe: "substantivo", gravidade: null },
  "xenofobia": { classe: "substantivo", gravidade: null },
  "xenofóbico": { classe: "adjetivo", gravidade: -2 },
  "xeretar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "xeretou", presente: "xereta", futuro: "xeretará" } },
  "xícara": { classe: "substantivo", gravidade: null },
  "xingar": { classe: "verbo", gravidade: -2, conjugacao: { passado: "xingou", presente: "xinga", futuro: "xingará" } },

  // Y
  "yakisoba": { classe: "substantivo", gravidade: null },
  "yang": { classe: "substantivo", gravidade: null },
  "yin": { classe: "substantivo", gravidade: null },
  "yoga": { classe: "substantivo", gravidade: null },

  // Z
  "zangado": { classe: "adjetivo", gravidade: -1 },
  "zangar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "zangou", presente: "zanga", futuro: "zangará" } },
  "zelar": { classe: "verbo", gravidade: 2, conjugacao: { passado: "zelou", presente: "zela", futuro: "zelará" } },
  "zelo": { classe: "substantivo", gravidade: null },
  "zeloso": { classe: "adjetivo", gravidade: 1 },
  "zênite": { classe: "substantivo", gravidade: null },
  "zero": { classe: "substantivo", gravidade: null },
  "zibelina": { classe: "substantivo", gravidade: null },
  "ziguezague": { classe: "substantivo", gravidade: null },
  "zombar": { classe: "verbo", gravidade: -1, conjugacao: { passado: "zombou", presente: "zomba", futuro: "zombará" } },
  "zombaria": { classe: "substantivo", gravidade: null },
  "zona": { classe: "substantivo", gravidade: null },
  "zumbar": { classe: "verbo", gravidade: 0, conjugacao: { passado: "zumbiu", presente: "zumbe", futuro: "zumbirá" } }
};