const JOGOS = [
  { nome: "Sonho", Dourado: false },
  { nome: "Cavar", Dourado: false },
  { nome: "Panqueca", Dourado: false },
  { nome: "Jogar cattoverse parte 1", Dourado: false },
  { nome: "Jogar cattoverse parte 2", Dourado: false },
  { nome: "Ritual de Beatbox", Dourado: true },
  { nome: "Maluco", Dourado: false },
  { nome: "Nightcore Desktop parte 1", Dourado: true },
  { nome: "Nightcore Desktop parte 2", Dourado: true },
  { nome: "88", Dourado: false },
  { nome: "Armadilha", Dourado: false },
  { nome: "Boca", Dourado: true },
  { nome: "Botão na praia", Dourado: false },
  { nome: "Matemática", Dourado: false },
  { nome: "Móveis enbocanhadores", Dourado: false },
  { nome: "Escola gritante parte 1", Dourado: false },
  { nome: "Escola gritante parte 2", Dourado: false },
  { nome: "Basquete", Dourado: false },
  { nome: "Batalha", Dourado: false },
  { nome: "Cartas", Dourado: false },
  { nome: "Estômago-lar", Dourado: false },
  { nome: "Construção e destruição", Dourado: false },
  { nome: "Parkour", Dourado: false },
  { nome: "Astronauta", Dourado: false },
  { nome: "Foguete-bomba", Dourado: false }
];

window.CODIGOS = {
  "Sonho": "1202261TO",
  "Cavar": "1302261TO",
  "Panqueca": "2002261TO",
  "Jogar cattoverse parte 1": "2402261TO",
  "Jogar cattoverse parte 2": "2402261TO",
  "Ritual de Beatbox": "2602261TO",
  "Maluco": "2702261TO",
  "Nightcore Desktop parte 1": "0403261TO",
  "Nightcore Desktop parte 2": "0403261TO",
  "88": "1603261TO",
  "Armadilha": "2603261TO",
  "Boca": "1604261TO",
  "Botão na praia": "2304261TO",
  "Matemática": "0605261TO",
  "Móveis enbocanhadores": "0705261TO",
  "Escola gritante parte 1": "1305261TO",
  "Escola gritante parte 2": "1305261TO",
  "Basquete": "1405261TO",
  "Batalha": "2205261TO",
  "Cartas": "2605261TO",
  "Estômago-lar": "2605262TO",
  "Construção e destruição": "2705261TO",
  "Parkour": "2905261TO",
  "Astronauta": "2905262TO",
  "Foguete-bomba": "0306261TO"
};