const JOGOS = [
  { nome: "Sonho", Dourado: false },
  { nome: "Cavar", Dourado: false },
  { nome: "Panqueca", Dourado: false },
  { nome: "Jogar cattoverse parte 1", Dourado: false },
  { nome: "Jogar cattoverse parte 2", Dourado: false },
  { nome: "Ritual de Beatbox", Dourado: true },
  { nome: "Maluco", Dourado: false },
  { nome: "Nightcore Desktop parte 1", Dourado: true },
  { nome: "Nightcore Desktop parte 2", Dourado: true },
  { nome: "88", Dourado: false },
  { nome: "Armadilha", Dourado: false },
  { nome: "Boca", Dourado: true },
  { nome: "Botão na praia", Dourado: false },
  { nome: "Matemática", Dourado: false },
  { nome: "Móveis enbocanhadores", Dourado: false },
  { nome: "Escola gritante parte 1", Dourado: false },
  { nome: "Escola gritante parte 2", Dourado: false },
  { nome: "Basquete", Dourado: false },
  { nome: "Batalha", Dourado: false },
  { nome: "Cartas", Dourado: false },
  { nome: "Estômago-lar", Dourado: false },
  { nome: "Construção e destruição", Dourado: false },
  { nome: "Parkour", Dourado: false },
  { nome: "Astronauta", Dourado: false },
  { nome: "Foguete-bomba", Dourado: false },
  { nome: "Rivalidade estomacal total parte 1", Dourado: false },
  { nome: "Rivalidade estomacal total parte 2", Dourado: false },
  { nome: "Bebês parte 1", Dourado: true },
  { nome: "Bebês parte 2", Dourado: true },
  { nome: "Acampamento", Dourado: false },
  { nome: "Caixa com maçã", Dourado: false },
  { nome: "A cola mais forte do mundo", Dourado: false },
  { nome: "Laser gun", Dourado: false },
  { nome: "Ser um cientista", Dourado: false},
  { nome: "Engarrafamento", Dourado: false},
  { nome: "Fósseis", Dourado: false},
  { nome: "Mukbang", Dourado: false},
  { nome: "Sendo cuidado PORQUE", Dourado: false},
  { nome: "Máquina do tempo parte 1", Dourado: true},
  { nome: "Máquina do tempo parte 2", Dourado: true},
  { nome: "Pause!", Dourado: false},
  { nome: "Sequestrar", Dourado: false},
  { nome: "Por dentro", Dourado: false},
  { nome: "Pintar", Dourado: false},
  { nome: "Universos cruzando", Dourado: false},
  { nome: "Sanduíche", Dourado: false},
  { nome: "Festa junina", Dourado: false},
  { nome: "Máquina de qualquer coisa parte 1", Dourado: false},
  { nome: "Máquina de qualquer coisa parte 2", Dourado: false},
  { nome: "Máquina de qualquer coisa parte 3", Dourado: false}
];

window.CODIGOS = {
  "Sonho": "1202261TO",
  "Cavar": "1302261TO",
  "Panqueca": "2002261TO",
  "Jogar cattoverse parte 1": "2402261TO",
  "Jogar cattoverse parte 2": "2402261TO",
  "Ritual de Beatbox": "2602261TO",
  "Maluco": "2702261TO",
  "Nightcore Desktop parte 1": "0403261TO",
  "Nightcore Desktop parte 2": "0403261TO",
  "88": "1603261TO",
  "Armadilha": "2603261TO",
  "Boca": "1604261TO",
  "Botão na praia": "2304261TO",
  "Matemática": "0605261TO",
  "Móveis enbocanhadores": "0705261TO",
  "Escola gritante parte 1": "1305261TO",
  "Escola gritante parte 2": "1305261TO",
  "Basquete": "1405261TO",
  "Batalha": "2205261TO",
  "Cartas": "2605261TO",
  "Estômago-lar": "2605262TO",
  "Construção e destruição": "2705261TO",
  "Parkour": "2905261TO",
  "Astronauta": "2905262TO",
  "Foguete-bomba": "0306261TO",
  "Rivalidade estomacal total parte 1": "0706261TO",
  "Rivalidade estomacal total parte 2": "0706261TO",
  "Bebês parte 1": "1905261TO",
  "Bebês parte 2": "1905261TO",
  "Acampamento": "1905262TO",
  "Caixa com maçã": "2005261TO",
  "A cola mais forte do mundo": "2105261TO",
  "Laser gun": "0806261TO",
  "Ser um cientista": "1006261TO",
  "Engarrafamento": "1006262TO",
  "Fósseis": "1006263TO",
  "Mukbang": "1106261TO",
  "Sendo cuidado PORQUE": "1206261TO",
  "Máquina do tempo parte 1": "1406261TO",
  "Máquina do tempo parte 2": "1406261TO",
  "Pause!": "1706261TO",
  "Sequestrar": "1806261TO",
  "Por dentro": "1806262TO",
  "Pintar": "1906261TO",
  "Universos cruzando": "2206261TO",
  "Sanduíche": "2306262TO",
  "Festa junina": "2406261TO",
  "Máquina de qualquer coisa parte 1": "2606261TO",
  "Máquina de qualquer coisa parte 2": "2606261TO",
  "Máquina de qualquer coisa parte 3": "2606261TO"
};